/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_rpc.h"

bool_t
print_rpc_1_svc(char *arg1, int *result, struct svc_req *rqstp) {


    printf("%s\n", arg1);

    return 1;
}

int
servidor_rpc_1_freeresult(SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result) {
    xdr_free(xdr_result, result);

    /*
     * Insert additional freeing code here, if needed
     */

    return 1;
}
